"""Pure data models for agent identity and output."""

from __future__ import annotations

from pydantic import BaseModel


class AgentDefinition(BaseModel):
    """An expert agent generated by the Recruiter in Phase 0."""

    agent_id: str
    role_title: str
    base_persona: str
    system_prompt: str = ""


class ExpertBrief(BaseModel):
    """An agent's independent conclusion from Phase 2."""

    agent_id: str
    role_title: str
    content: str
